; Tela inteira 30x40
; Interface
Screen_1_Line0 : string " ______________________________________ " ; 0
Screen_1_Line1 : string "|                                      |" ; 40
Screen_1_Line2 : string "|                                      |" ; 80
Screen_1_Line3 : string "|                                      |" ; 120
Screen_1_Line4 : string "|                                      |" ; 160
Screen_1_Line5 : string "|                                      |" ; 200
Screen_1_Line6 : string "|                                      |" ; 240
Screen_1_Line7 : string "|                                      |" ; 280
Screen_1_Line8 : string "|                                      |" ; 320
Screen_1_Line9 : string "|                                      |" ; 360
Screen_1_Line10: string "|                                      |" ; 400
Screen_1_Line11: string "|                                      |" ; 440
Screen_1_Line12: string "|                                      |" ; 480
Screen_1_Line13: string "|                                      |" ; 520
Screen_1_Line14: string "|                                      |" ; 560
Screen_1_Line15: string "|                                      |" ; 600
Screen_1_Line16: string "|                                      |" ; 640
Screen_1_Line17: string "|                                      |" ; 680
Screen_1_Line18: string "|                                      |" ; 720
Screen_1_Line19: string "|                                      |" ; 760
Screen_1_Line20: string "|______________________________________|" ; 800
Screen_1_Line21: string "                                        " ; 840
Screen_1_Line22: string "                                        " ; 880
Screen_1_Line23: string "                                        " ; 920
Screen_1_Line24: string " ______________________________________ " ; 960
Screen_1_Line25: string "|                                      |" ; 1000
Screen_1_Line26: string "|                                      |" ; 1040
Screen_1_Line27: string "|                                      |" ; 1080
Screen_1_Line28: string "|                                      |" ; 1120
Screen_1_Line29: string "|______________________________________|" ; 1160

; Forca inicial
Screen_2_Line0 : string "                                        "
Screen_2_Line1 : string "                                        "
Screen_2_Line2 : string "                                        "
Screen_2_Line3 : string "   ______________________               "
Screen_2_Line4 : string "   HH####################               "
Screen_2_Line5 : string "   HH                                   "
Screen_2_Line6 : string "   HH                                   "
Screen_2_Line7 : string "   HH                                   "
Screen_2_Line8 : string "   HH                                   "
Screen_2_Line9 : string "   HH                                   "
Screen_2_Line10: string "   HH                                   "
Screen_2_Line11: string "   HH                                   "
Screen_2_Line12: string "   HH                                   "
Screen_2_Line13: string "   HH____________________________       "
Screen_2_Line14: string "   HH#######0          0#########       "
Screen_2_Line15: string "   HH\\\\  //HH          HH\\\\  //HH       "
Screen_2_Line16: string "   HH \\\\// HH          HH \\\\// HH       "
Screen_2_Line17: string "   HH  HH  HH          HH  HH  HH       "
Screen_2_Line18: string "   HH //\\\\ HH          HH //\\\\ HH       "
Screen_2_Line19: string "   HH//  \\\\HH          HH//  \\\\HH       "
Screen_2_Line21: string "                                        "
Screen_2_Line20: string "                                        "
Screen_2_Line22: string "                                        "
Screen_2_Line23: string "                                        "
Screen_2_Line24: string "                                        "
Screen_2_Line25: string "                                        "
Screen_2_Line26: string "                                        "
Screen_2_Line27: string "                                        "
Screen_2_Line28: string "                                        "
Screen_2_Line29: string "                                        "
; Forca inteira aberta
Screen_3_Line0 : string "                                        "
Screen_3_Line1 : string "                                        "
Screen_3_Line2 : string "                                        "
Screen_3_Line3 : string "   ______________________               "
Screen_3_Line4 : string "   HH####################               "
Screen_3_Line5 : string "   HH                                   "
Screen_3_Line6 : string "   HH                                   "
Screen_3_Line7 : string "   HH                                   "
Screen_3_Line8 : string "   HH                                   "
Screen_3_Line9 : string "   HH                                   "
Screen_3_Line10: string "   HH                                   "
Screen_3_Line11: string "   HH                                   "
Screen_3_Line12: string "   HH                                   "
Screen_3_Line13: string "   HH________          __________       "
Screen_3_Line14: string "   HH#######0|        |0#########       "
Screen_3_Line15: string "   HH\\\\  //HH|        |HH\\\\  //HH       "
Screen_3_Line16: string "   HH \\\\// HH|        |HH \\\\// HH       "
Screen_3_Line17: string "   HH  HH  HH|        |HH  HH  HH       "
Screen_3_Line18: string "   HH //\\\\ HH|        |HH //\\\\ HH       "
Screen_3_Line19: string "   HH//  \\\\HH          HH//  \\\\HH       "
Screen_3_Line21: string "                                        "
Screen_3_Line20: string "                                        "
Screen_3_Line22: string "                                        "
Screen_3_Line23: string "                                        "
Screen_3_Line24: string "                                        "
Screen_3_Line25: string "                                        "
Screen_3_Line26: string "                                        "
Screen_3_Line27: string "                                        "
Screen_3_Line28: string "                                        "
Screen_3_Line29: string "                                        "
; pessoa nao enforcada
Screen_4_Line0 : string "                                        "
Screen_4_Line1 : string "                                        "
Screen_4_Line2 : string "                                        "
Screen_4_Line3 : string "                                        "
Screen_4_Line4 : string "                                        "
Screen_4_Line5 : string "                 (                      "
Screen_4_Line6 : string "                 )                      "
Screen_4_Line7 : string "                 (                      "
Screen_4_Line8 : string "                 )                      "
Screen_4_Line9 : string "                                        "
Screen_4_Line10: string "                                        "
Screen_4_Line11: string "                                        "
Screen_4_Line12: string "                                        "
Screen_4_Line13: string "                                        "
Screen_4_Line14: string "                                        "
Screen_4_Line15: string "                                        "
Screen_4_Line16: string "                                        "
Screen_4_Line17: string "                                        "
Screen_4_Line18: string "                                        "
Screen_4_Line19: string "                                        "
Screen_4_Line20: string "                                        "
Screen_4_Line21: string "                                        "
Screen_4_Line22: string "                                        "
Screen_4_Line23: string "                                        "
Screen_4_Line24: string "                                        "
Screen_4_Line25: string "                                        "
Screen_4_Line26: string "                                        "
Screen_4_Line27: string "                                        "
Screen_4_Line28: string "                                        "
Screen_4_Line29: string "                                        "

; pessoa
Screen_5_Line0 : string "                                        "
Screen_5_Line1 : string "                                        "
Screen_5_Line2 : string "                                        "
Screen_5_Line3 : string "                                        "
Screen_5_Line4 : string "                                        "
Screen_5_Line5 : string "                                        "
Screen_5_Line6 : string "                                        "
Screen_5_Line7 : string "                                        "
Screen_5_Line8 : string "                                        "
Screen_5_Line9 : string "                ( )                     "
Screen_5_Line10: string "                                        "
Screen_5_Line11: string "                                        "
Screen_5_Line12: string "                                        "
Screen_5_Line13: string "                                        "
Screen_5_Line14: string "                                        "
Screen_5_Line15: string "                                        "
Screen_5_Line16: string "                                        "
Screen_5_Line17: string "                                        "
Screen_5_Line18: string "                                        "
Screen_5_Line19: string "                                        "
Screen_5_Line20: string "                                        "
Screen_5_Line21: string "                                        "
Screen_5_Line22: string "                                        "
Screen_5_Line23: string "                                        "
Screen_5_Line24: string "                                        "
Screen_5_Line25: string "                                        "
Screen_5_Line26: string "                                        "
Screen_5_Line27: string "                                        "
Screen_5_Line28: string "                                        "
Screen_5_Line29: string "                                        "

; pessoa
Screen_6_Line0 : string "                                        "
Screen_6_Line1 : string "                                        "
Screen_6_Line2 : string "                                        "
Screen_6_Line3 : string "                                        "
Screen_6_Line4 : string "                                        "
Screen_3_Line5 : string "                                        "
Screen_6_Line6 : string "                                        "
Screen_6_Line7 : string "                                        "
Screen_6_Line8 : string "                                        "
Screen_6_Line9 : string "                ( )                     "
Screen_6_Line10: string "                 W                      "
Screen_6_Line11: string "                 A                      "
Screen_6_Line12: string "                                        "
Screen_6_Line13: string "                                        "
Screen_6_Line14: string "                                        "
Screen_6_Line15: string "                                        "
Screen_6_Line16: string "                                        "
Screen_6_Line17: string "                                        "
Screen_6_Line18: string "                                        "
Screen_6_Line19: string "                                        "
Screen_6_Line20: string "                                        "
Screen_6_Line21: string "                                        "
Screen_6_Line22: string "                                        "
Screen_6_Line23: string "                                        "
Screen_6_Line24: string "                                        "
Screen_6_Line25: string "                                        "
Screen_6_Line26: string "                                        "
Screen_6_Line27: string "                                        "
Screen_6_Line28: string "                                        "
Screen_6_Line29: string "                                        "

; pessoa
Screen_7_Line0 : string "                                        "
Screen_7_Line1 : string "                                        "
Screen_7_Line2 : string "                                        "
Screen_7_Line3 : string "                                        "
Screen_7_Line4 : string "                                        "
Screen_7_Line5 : string "                                        "
Screen_7_Line6 : string "                                        "
Screen_7_Line7 : string "                                        "
Screen_7_Line8 : string "                                        "
Screen_7_Line9 : string "                ( )                     "
Screen_7_Line10: string "                 W                      "
Screen_7_Line11: string "                 A                      "
Screen_7_Line12: string "                  \\                     "
Screen_7_Line13: string "                   L                    "
Screen_7_Line14: string "                                        "
Screen_7_Line15: string "                                        "
Screen_7_Line16: string "                                        "
Screen_7_Line17: string "                                        "
Screen_7_Line18: string "                                        "
Screen_7_Line19: string "                                        "
Screen_7_Line20: string "                                        "
Screen_7_Line21: string "                                        "
Screen_7_Line22: string "                                        "
Screen_7_Line23: string "                                        "
Screen_7_Line24: string "                                        "
Screen_7_Line25: string "                                        "
Screen_7_Line26: string "                                        "
Screen_7_Line27: string "                                        "
Screen_7_Line28: string "                                        "
Screen_7_Line29: string "                                        "

; pessoa
Screen_8_Line0 : string "                                        "
Screen_8_Line1 : string "                                        "
Screen_8_Line2 : string "                                        "
Screen_8_Line3 : string "                                        "
Screen_8_Line4 : string "                                        "
Screen_8_Line5 : string "                                        "
Screen_8_Line6 : string "                                        "
Screen_8_Line7 : string "                                        "
Screen_8_Line8 : string "                                        "
Screen_8_Line9 : string "                ( )                     "
Screen_8_Line10: string "                 W                      "
Screen_8_Line11: string "                 A                      "
Screen_8_Line12: string "                / \\                     "
Screen_8_Line13: string "               J   L                    "
Screen_8_Line14: string "                                        "
Screen_8_Line15: string "                                        "
Screen_8_Line16: string "                                        "
Screen_8_Line17: string "                                        "
Screen_8_Line18: string "                                        "
Screen_8_Line19: string "                                        "
Screen_8_Line20: string "                                        "
Screen_8_Line21: string "                                        "
Screen_8_Line22: string "                                        "
Screen_8_Line23: string "                                        "
Screen_8_Line24: string "                                        "
Screen_8_Line25: string "                                        "
Screen_8_Line26: string "                                        "
Screen_8_Line27: string "                                        "
Screen_8_Line28: string "                                        "
Screen_8_Line29: string "                                        "

; pessoa
Screen_9_Line0 : string "                                        "
Screen_9_Line1 : string "                                        "
Screen_9_Line2 : string "                                        "
Screen_9_Line3 : string "                                        "
Screen_9_Line4 : string "                                        "
Screen_9_Line5 : string "                                        "
Screen_9_Line6 : string "                                        "
Screen_9_Line7 : string "                                        "
Screen_9_Line8 : string "                                        "
Screen_9_Line9 : string "                ( )                     "
Screen_9_Line10: string "                 W\\                     "
Screen_9_Line11: string "                 A                      "
Screen_9_Line12: string "                / \\                     "
Screen_9_Line13: string "               J   L                    "
Screen_9_Line14: string "                                        "
Screen_9_Line15: string "                                        "
Screen_9_Line16: string "                                        "
Screen_9_Line17: string "                                        "
Screen_9_Line18: string "                                        "
Screen_9_Line19: string "                                        "
Screen_9_Line20: string "                                        "
Screen_9_Line21: string "                                        "
Screen_9_Line22: string "                                        "
Screen_9_Line23: string "                                        "
Screen_9_Line24: string "                                        "
Screen_9_Line25: string "                                        "
Screen_9_Line26: string "                                        "
Screen_9_Line27: string "                                        "
Screen_9_Line28: string "                                        "
Screen_9_Line29: string "                                        "

; pessoa
Screen_10_Line0 : string "                                        "
Screen_10_Line1 : string "                                        "
Screen_10_Line2 : string "                                        "
Screen_10_Line3 : string "                                        "
Screen_10_Line4 : string "                                        "
Screen_10_Line5 : string "                                        "
Screen_10_Line6 : string "                                        "
Screen_10_Line7 : string "                                        "
Screen_10_Line8 : string "                                        "
Screen_10_Line9 : string "                ( )                     "
Screen_10_Line10: string "                /W\\                     "
Screen_10_Line11: string "                 A                      "
Screen_10_Line12: string "                / \\                     "
Screen_10_Line13: string "               J   L                    "
Screen_10_Line14: string "                                        "
Screen_10_Line15: string "                                        "
Screen_10_Line16: string "                                        "
Screen_10_Line17: string "                                        "
Screen_10_Line18: string "                                        "
Screen_10_Line19: string "                                        "
Screen_10_Line20: string "                                        "
Screen_10_Line21: string "                                        "
Screen_10_Line22: string "                                        "
Screen_10_Line23: string "                                        "
Screen_10_Line24: string "                                        "
Screen_10_Line25: string "                                        "
Screen_10_Line26: string "                                        "
Screen_10_Line27: string "                                        "
Screen_10_Line28: string "                                        "
Screen_10_Line29: string "                                        "

; pessoa enforcada
Screen_11_Line0 : string "                                        "
Screen_11_Line1 : string "                                        "
Screen_11_Line2 : string "                                        "
Screen_11_Line3 : string "                                        "
Screen_11_Line4 : string "                                        "
Screen_11_Line5 : string "                                        "
Screen_11_Line6 : string "                                        "
Screen_11_Line7 : string "                                        "
Screen_11_Line8 : string "                                        "
Screen_11_Line9 : string "                                        "
Screen_11_Line10: string "                                        "
Screen_11_Line11: string "                                        "
Screen_11_Line12: string "                ( )                     "
Screen_11_Line13: string "                /W\\                     "
Screen_11_Line14: string "                 A                      "
Screen_11_Line15: string "                / \\                     "
Screen_11_Line16: string "               J   L                    "
Screen_11_Line17: string "                                        "
Screen_11_Line18: string "                                        "
Screen_11_Line19: string "                                        "
Screen_11_Line20: string "                                        "
Screen_11_Line21: string "                                        "
Screen_11_Line22: string "                                        "
Screen_11_Line23: string "                                        "
Screen_11_Line24: string "                                        "
Screen_11_Line25: string "                                        "
Screen_11_Line26: string "                                        "
Screen_11_Line27: string "                                        "
Screen_11_Line28: string "                                        "
Screen_11_Line29: string "                                        "

; fogo
Screen_12_Line0 : string "                                        "
Screen_12_Line1 : string "                                        "
Screen_12_Line2 : string "                                        "
Screen_12_Line3 : string "                                        "
Screen_12_Line4 : string "                                        "
Screen_12_Line5 : string "                                        "
Screen_12_Line6 : string "                                        "
Screen_12_Line7 : string "                                        "
Screen_12_Line8 : string "                                        "
Screen_12_Line9 : string "                                        "
Screen_12_Line10: string "                                        "
Screen_12_Line11: string "                                        "
Screen_12_Line12: string "                                        "
Screen_12_Line13: string "                                        "
Screen_12_Line14: string "                                        "
Screen_12_Line15: string "                                        "
Screen_12_Line16: string "                                        "
Screen_12_Line17: string "                 A                      "
Screen_12_Line18: string "              /\\/A\\A                    "
Screen_12_Line19: string "              A/AXHX\\A                  "
Screen_12_Line21: string "                                        "
Screen_12_Line20: string "                                        "
Screen_12_Line22: string "                                        "
Screen_12_Line23: string "                                        "
Screen_12_Line24: string "                                        "
Screen_12_Line25: string "                                        "
Screen_12_Line26: string "                                        "
Screen_12_Line27: string "                                        "
Screen_12_Line28: string "                                        "
Screen_12_Line29: string "                                        "

Screen_13_Line0 : string "                                        "
Screen_13_Line1 : string "                                        "
Screen_13_Line2 : string "                                        "
Screen_13_Line3 : string "                                        "
Screen_13_Line4 : string "                                        "
Screen_13_Line5 : string "                 (                      "
Screen_13_Line6 : string "                 )                      "
Screen_13_Line7 : string "                 (                      "
Screen_13_Line8 : string "                 (                      "
Screen_13_Line9 : string "                 )                      "
Screen_13_Line10: string "                 (                      "
Screen_13_Line11: string "                 )                      "
Screen_13_Line12: string "                                        "
Screen_13_Line13: string "                                        "
Screen_13_Line14: string "                                        "
Screen_13_Line15: string "                                        "
Screen_13_Line16: string "                                        "
Screen_13_Line17: string "                                        "
Screen_13_Line18: string "                                        "
Screen_13_Line19: string "                                        "
Screen_13_Line21: string "                                        "
Screen_13_Line20: string "                                        "
Screen_13_Line22: string "                                        "
Screen_13_Line23: string "                                        "
Screen_13_Line24: string "                                        "
Screen_13_Line25: string "                                        "
Screen_13_Line26: string "                                        "
Screen_13_Line27: string "                                        "
Screen_13_Line28: string "                                        "
Screen_13_Line29: string "                                        "